name: Deploy React. Application

on: 
  push:
    branches: [main]
    
jobs:
  build-deploy:
    runs-on: amazonlinux2
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Build React App
        run: npm run build
      #Deploy to S3
      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: aws s3 sync ./dist s3://sylvia-react-pipeline-bucket --delete
    
  
