name: Deploy React. Application

on: 
  push:
    branches: [main]
    
jobs:
  runs-on: amazonlinux2
  steps:
    - uses: actions/checkout@v3
    - name: Install Packages
    run: npm install
    - name: Build React App
    run: npm run build
    #Deploy to S3
  
